class GroupModel {
  String groupName;
  String groupID; //" to groupID,
  String faceUrl; //" to faceUrl,
  String groupType; //" to groupType,
  String introduction; //" to introduction,
  String notification; //" to notification,
  String owner; //" to owner,
  int createTime; //" to createTime,
  int memberCount; //" to memberCount,
  int lastMessageTime; //" to lastMessageTime,
  bool isAllMuted; //" to isAllMuted,
  int recvOpt; //" to recvOpt,
  int role = 0; //" to role,
  int groupAddOpt; //" to groupAddOpt,
  int lastInfoTime; //" to lastInfoTime,
  int onlineCount; //" to onlineCount,
  int joinTime; //" to joinTime,

  Map<String, dynamic> toJson() => {
        "groupName": groupName,
        "groupID": groupID,
        "faceUrl": faceUrl,
        "groupType": groupType,
        "introduction": introduction,
        "notification": notification,
        "owner": owner,
        "createTime": createTime,
        "memberCount": memberCount,
        "lastMessageTime": lastMessageTime,
        "isAllMuted": isAllMuted,
        "recvOpt": recvOpt,
        "role": role,
        "groupAddOpt": groupAddOpt,
        "lastInfoTime": lastInfoTime,
        "onlineCount": onlineCount,
        "joinTime": joinTime,
      };

  GroupModel.fromJson(Map<String, dynamic> json)
      : groupName = json["groupName"],
        groupID = json["groupID"],
        faceUrl = json["faceUrl"],
        groupType = json["groupType"],
        introduction = json["introduction"],
        notification = json["notification"],
        createTime = json["createTime"],
        memberCount = json["memberCount"],
        lastMessageTime = json["lastMessageTime"],
        isAllMuted = json["isAllMuted"],
        recvOpt = json["recvOpt"],
        role = json["role"],
        groupAddOpt = json["groupAddOpt"],
        lastInfoTime = json["lastInfoTime"],
        onlineCount = json["onlineCount"],
        joinTime = json["joinTime"],
        owner = json["owner"];
}
